"""Runtime lookups for the offline-calibrated strength/equity tables.

`evaluate_relative_strength` returns a fast 0..1 heuristic score, not a win
probability, and it is blind to how many opponents are still in the hand. Comparing
that score directly against pot odds -- as the strategy used to -- compares two
different quantities. These tables map the score onto measured equity by street and
opponent count, at dictionary-lookup cost.

If the generated tables are missing the lookups degrade to the identity, which
reproduces the previous behaviour rather than breaking the agent.
"""
from __future__ import annotations
import math
from typing import Any
from .cards import Card, RV, evaluate_relative_strength

try:  # generated by scratch/build_calibration.py
    from .calibration_data import BINS, PREFLOP_PERCENTILE, POSTFLOP_EQUITY
except Exception:  # pragma: no cover
    BINS = 0
    PREFLOP_PERCENTILE: dict[str, float] = {}
    POSTFLOP_EQUITY: dict[str, list[float]] = {}

_OPPONENT_KEYS = (1, 2, 3, 4, 5)
_RANK_CHAR: dict[int, str] = {
    2: "2", 3: "3", 4: "4", 5: "5", 6: "6", 7: "7", 8: "8", 9: "9",
    10: "T", 11: "J", 12: "Q", 13: "K", 14: "A",
}


def hand_class(hero: list[Card]) -> str:
    """Canonical 169-bucket name for a two-card holding, e.g. 'AKs', 'QQo', 'T9o'."""
    c0, c1 = hero[0], hero[1]
    r0, r1 = c0.rank, c1.rank
    if r0 >= r1:
        hi, lo = r0, r1
    else:
        hi, lo = r1, r0
    c_hi = _RANK_CHAR.get(hi, "2")
    c_lo = _RANK_CHAR.get(lo, "2")
    suited = c0.suit == c1.suit
    return c_hi + c_lo + ("s" if suited and hi != lo else "o")


def preflop_percentile(hero: list[Card]) -> float | None:
    """Percentile of this starting hand among all 169 classes (1.0 = strongest).

    This is what makes a VPIP target meaningful: "play the top X% of hands" becomes a
    direct comparison instead of a guess at a threshold on an uncalibrated score.
    """
    if len(hero) != 2 or not PREFLOP_PERCENTILE:
        return None
    return PREFLOP_PERCENTILE.get(hand_class(hero))


def strength_to_equity(street: int, opponents: int, strength: float, interpolate: bool = False) -> float:
    """Map a heuristic postflop strength onto measured equity vs `opponents` hands.

    Guarantees:
    - O(1) table lookup with boundary clamping.
    - Streets >= 5 mapped to 5 (river).
    - Opponents clamped to [1, 5].
    - Safe against NaN and out-of-range floats.
    """
    if not POSTFLOP_EQUITY or street < 3:
        return strength
    if math.isnan(strength):
        return 0.5
    s_clamped = max(0.0, min(1.0, float(strength)))
    st = min(5, max(3, int(street)))
    n = min(_OPPONENT_KEYS[-1], max(_OPPONENT_KEYS[0], int(opponents)))
    table = POSTFLOP_EQUITY.get(f"{st}:{n}")
    if not table or BINS <= 0:
        return s_clamped

    if not interpolate:
        idx = int(s_clamped * BINS)
        if idx < 0:
            idx = 0
        elif idx >= BINS:
            idx = BINS - 1
        return table[idx]

    # Smooth continuous linear interpolation
    pos = s_clamped * (BINS - 1)
    idx = int(pos)
    if idx >= BINS - 1:
        return table[-1]
    frac = pos - idx
    return (1.0 - frac) * table[idx] + frac * table[idx + 1]


def fast_equity(hero: list[Card], board: list[Card], opponents: int = 1, interpolate: bool = False) -> float:
    """Convenience evaluator combining heuristic strength and calibrated equity lookup."""
    street = len(board)
    if street < 3:
        pct = preflop_percentile(hero)
        return pct if pct is not None else 0.5
    raw = evaluate_relative_strength(hero, board)["strength"]
    return strength_to_equity(street, opponents, raw, interpolate=interpolate)


def has_tables() -> bool:
    return bool(PREFLOP_PERCENTILE) and bool(POSTFLOP_EQUITY)

